### ISSUE TITLE
10.15.2 及以后版本不可用

### ISSUE THREAD

**Issue by Goooler** [portrayer/Hackintosh-Ryzen-MSI-B450I#10]
10.15.2 及以后版本无法安装，似乎需要迁移到 oc，老哥有时间弄一下吗，我觉得可以先开个 oc 的分支

**Comment by portrayer** [comment]
主机暂时没在身边，需要过一段时间在处理了，OC目前我也还不太熟悉

**Comment by Goooler** [comment]
一样不在身边，等会去之后我看看

**Comment by Fidelity88** [comment]
I managed to get it working in OpenCore. It's not that hard actually.
Only thing that doesn't work until now is Wifi and Bluetooth. But I'm still trying at the moment :) Just follow the OpenCore documentation to get everything working!

**Comment by Goooler** [comment]
> I managed to get it working in OpenCore. It's not that hard actually.
> Only thing that doesn't work until now is Wifi and Bluetooth. But I'm still trying at the moment :) Just follow the OpenCore documentation to get everything working!

could you please share your efi folder ?

**Comment by Goooler** [comment]
> 主机暂时没在身边，需要过一段时间在处理了，OC目前我也还不太熟悉

我把 oc 搞定了，把仓库重命名一下，开个 oc 的分支吧，我交个 pr 上去

**Comment by portrayer** [comment]
> > 主机暂时没在身边，需要过一段时间在处理了，OC目前我也还不太熟悉
> 
> 我把 oc 搞定了，把仓库重命名一下，开个 oc 的分支吧，我交个 pr 上去

巧了，我这两天刚把OC搞好，你对比下看看

**Comment by Goooler** [comment]
> > > 主机暂时没在身边，需要过一段时间在处理了，OC目前我也还不太熟悉
> > 
> > 
> > 我把 oc 搞定了，把仓库重命名一下，开个 oc 的分支吧，我交个 pr 上去
> 
> 巧了，我这两天刚把OC搞好，你对比下看看

老哥是一个盘内双系统吧，我是黑苹果单独一个盘，用你的配置无法启动 windows 了

**Comment by portrayer** [comment]
> 用你的配置无法启动 windows 了

windows的efi是另外的分区吗？我是一个盘，理论上你把win的efi下的Microsoft放到OC的EFI下应该就可以了

**Comment by Goooler** [comment]
> windows的efi是另外的分区吗？我是一个盘，理论上你把win的efi下的Microsoft放到OC的EFI下应该就可以了

还是不行，无法启动，我觉着双系统的话还是双 efi 分区吧，让 oc 自己去扫描引导，这样通用型更强一点，出了错也不影响单独 引导 win

**Comment by portrayer** [comment]
opencore updated
