### ISSUE TITLE
Wifi + Bluetooth on OpenCore

### ISSUE THREAD

**Issue by Fidelity88** [portrayer/Hackintosh-Ryzen-MSI-B450I#18]
Hi @Goooler 

does Wifi and Bluetooth on this board work with OpenCore?

The readme says the same since Clover, so I'm curious if anything changed here?
- WIFI by AirportBrcmFixup (brcmfx-country=#a)
- Bluetooth by BrcmPatchRAM and nickhx from osxlatitude

Did you replace the wifi card or is it the stock card? Thanks!

**Comment by Goooler** [comment]
> Hi @Goooler
> 
> does Wifi and Bluetooth on this board work with OpenCore?
> 
> The readme says the same since Clover, so I'm curious if anything changed here?
> 
> * WIFI by AirportBrcmFixup (brcmfx-country=#a)
> * Bluetooth by BrcmPatchRAM and nickhx from osxlatitude
> 
> Did you replace the wifi card or is it the stock card? Thanks!

If you need wifi or bluetooth should replace stock wifi card with DW1820A like what readme said
