### ISSUE TITLE
Fixed BT module not detected

### ISSUE THREAD

**Issue by Mushmuch** [portrayer/Hackintosh-Ryzen-MSI-B450I#23]
[Obelix-MSI b450i-EFIv2.zip](https://github.com/portrayer/Hackintosh-Ryzen-MSI-B450I/files/4708586/Obelix-MSI.b450i-EFIv2.zip)
Hi,

I made a SSDT to properly map the USB controller on the MSI b450i.
It allows to use the BT module in the Fenvi cards.
@

**Comment by portrayer** [comment]
do you use m.2 WIFI/BT card? in my case, usb map works well for my on-board wifi/bt card (I changed the original intel 3168 to dw1820a).

**Comment by Mushmuch** [comment]
Yes, I use a m.2 A&E caed based on BCM94352Z. The BT module appears under the PO12 port.
Under which port does your BT show up?

**Comment by portrayer** [comment]
PO12, too
