### ISSUE TITLE
Sleep not working

### ISSUE THREAD

**Issue by Mushmuch** [portrayer/Hackintosh-Ryzen-MSI-B450I#24]
Hi,
Does sleep work for you?
Best regards

**Comment by Mushmuch** [comment]
I had to disable the XHC0 controller with a SSDT to get sleep to work.
Does your hack sleep? If so, how did you do it?
I'm running the .AB0 firmware.

**Comment by portrayer** [comment]
no hacking, and sleep works well.
my bios version is 7A40vAB

**Comment by Mushmuch** [comment]
Do you have USB devices connected to the internal headers or the USB ports next to the Ethernet connector?

**Comment by portrayer** [comment]
no, no device connected to XHC0.

**Comment by Kaijun** [comment]
> Do you have USB devices connected to the internal headers or the USB ports next to the Ethernet connector?

same to me.

my mb is B350i, when i have my usb2.0 mouse/keyboard connected, it can sleep however the display could not turn on  after wake up.

i also fixed the usb mapping, but it doesn't help at all
