### ISSUE TITLE
  Could  you install matlab R2020a? 

### ISSUE THREAD

**Issue by sqlmap3** [portrayer/Hackintosh-Ryzen-MSI-B450I#26]

**Comment by portrayer** [comment]
never tried.

**Comment by sqlmap3** [comment]
I had installed it.[Reference: ](https://github.com/gtrfx/gtrfx.github.io/blob/6d8bd8c4a92e10972b5e7b3cfcb96dc4972d2fb0/_posts/2019/2019-nov/2019-11-17-amd-osx-matlab.md)
