### ISSUE TITLE
BIOS Settings

### ISSUE THREAD

**Issue by Huangqionghao** [portrayer/Hackintosh-Ryzen-MSI-B450I#27]
Dose it need a  further setting of BIOS? Cause I followed the instructions to install the os , and it failed.

**Comment by Mushmuch** [comment]
With the latest bios ending in “AB0”, the only  required change for me was to change Windows mode from CSM to UEFI.
If you let “Above 4G decoding” disabled for Windows, you must add the following boot argument to the NVRAM: npci=0x2000

**Comment by Goooler** [comment]
> Dose it need a further setting of BIOS? Cause I followed the instructions to install the os , and it failed.

what's your bios version?

**Comment by Huangqionghao** [comment]
> > Dose it need a further setting of BIOS? Cause I followed the instructions to install the os , and it failed.
> 
> what's your bios version?

The bios version is E7A40AMS.AA0, and the installation froze up without errors at "2 minutes left" .

**Comment by Goooler** [comment]
> The bios version is E7A40AMS.AA0, and the installation froze up without errors at "2 minutes left" .

You can upgrate bios to latest version and try again

**Comment by Huangqionghao** [comment]
> With the latest bios ending in “AB0”, the only required change for me was to change Windows mode from CSM to UEFI.
> If you let “Above 4G decoding” disabled for Windows, you must add the following boot argument to the NVRAM: npci=0x2000
Thanks, but it didn't work.

**Comment by Huangqionghao** [comment]
> > The bios version is E7A40AMS.AA0, and the installation froze up without errors at "2 minutes left" .
> 
> You can upgrate bios to latest version and try again

I tried it, but it failed again, by the way, my cpu is Ryzen 3600, and does it need an alternation to the config.plist?

**Comment by portrayer** [comment]
> > > The bios version is E7A40AMS.AA0, and the installation froze up without errors at "2 minutes left" .
> > 
> > 
> > You can upgrate bios to latest version and try again
> 
> I tried it, but it failed again, by the way, my cpu is Ryzen 3600, and does it need an alternation to the config.plist?

no need since vanilla patch is identical for ryzen.
make sure [windows os configuration] is set to UEFI and [Above 4G memory] disabled.

**Comment by Huangqionghao** [comment]
> > > > The bios version is E7A40AMS.AA0, and the installation froze up without errors at "2 minutes left" .
> > > 
> > > 
> > > You can upgrate bios to latest version and try again
> > 
> > 
> > I tried it, but it failed again, by the way, my cpu is Ryzen 3600, and does it need an alternation to the config.plist?
> 
> no need since vanilla patch is identical for ryzen.
> make sure [windows os configuration] is set to UEFI and [Above 4G memory] disabled.

Thanks for your reply, the configuration files are situtable for my desktop computer specifications, and I have used them as a bootloader for my hackintosh, and I still can not install the hackintosh from a usb driver with the same problems as aforementioned, but finally I installed the hackintosh with Paragon Hard Disk Manager 17 by restoring a backup image of hackintosh to my target hackintosh partition.
