### ISSUE TITLE
Sidecar... Blank / Black Screen

### ISSUE THREAD

**Issue by elmzelmz** [portrayer/Hackintosh-Ryzen-MSI-B450I#29]
hello.. do i need any kext / patch to make sidecar work..?

ipad can be detected but no image coming out, only the side bar is showing.

Thanks..

**Comment by portrayer** [comment]
I don't have sidecar devices, so never tested.

**Comment by Mushmuch** [comment]
Interesting, what did you do to get Sidecar to even slightly work?
I cannot even select my iPad, the dropdown shows "No Devices".
Which SMBIOS do you use?

**Comment by elmzelmz** [comment]
> Interesting, what did you do to get Sidecar to even slightly work?
> I cannot even select my iPad, the dropdown shows "No Devices".
> Which SMBIOS do you use?

iMacpro1.1
