### ISSUE TITLE
memory speed at full speed solution?

### ISSUE THREAD

**Issue by cgovella** [portrayer/Hackintosh-Ryzen-MSI-B450I#3]
I have this board, with 2x 8gb Corsair DDR4 3000mhz. Did you figure this out? I tried a couple things in CC. One was the Boot flag on XMP, fiddled with XMPDetection Yes/No/1/2, not sure if any of those did the trick, I rebooted, still incorrect speed, but left it on. The second thing was the SMBIOS page under Memory trying to add the memory sticks manually. Set the SlotCount to 4, Dual Channel, Slot 0 and Slot 2, with the size, freq, Vendor, part, and serial. That worked for me and now . See this page: https://www.tonymacx86.com/threads/guide-el-capitan-on-the-intel-skylake-nuc.183839/ 

Note that if you set SlotCount to 2, it won't boot.

**Comment by portrayer** [comment]
thanks for your information.
at this moment, just upgrade bios will fix this issue, should be a bug of msi.
