### ISSUE TITLE
 android and iOS development?

### ISSUE THREAD

**Issue by WilliamDaniel2406** [portrayer/Hackintosh-Ryzen-MSI-B450I#32]
do you use hackintosh for android development?
I need feedback because I plan to hackintosh with ryzen and would like feedback on performance and working comfort

**Comment by Goooler** [comment]
> performance

you can't use emulator in Adnroid Studio, just take replace with Genymotion

**Comment by Goooler** [comment]
> do you use hackintosh for android development?
> I need feedback because I plan to hackintosh with ryzen and would like feedback on performance and working comfort

you can't use emulator in Adnroid Studio, just take replace with Genymotion

**Comment by WilliamDaniel2406** [comment]
emulator iOS? Xcode? functional? or not?

**Comment by WilliamDaniel2406** [comment]
> > do you use hackintosh for android development?
> > I need feedback because I plan to hackintosh with ryzen and would like feedback on performance and working comfort
> 
> you can't use emulator in Adnroid Studio, just take replace with Genymotion

emulator iOS? Xcode? functional? or not?

**Comment by WilliamDaniel2406** [comment]
> you can't use emulator in Adnroid Studio, just take replace with Genymotion

emulator iOS ,Xcode? functional? or not?

**Comment by Goooler** [comment]
> emulator iOS ,Xcode? functional? or not?

any emulator which use Intel VT instruction could not work in ryzen hackintosh

**Comment by portrayer** [comment]
> > you can't use emulator in Adnroid Studio, just take replace with Genymotion
> 
> emulator iOS ,Xcode? functional? or not?

iOS emulator works. android should use genymotion & virtualbox and open amd-v in bios.
