### ISSUE TITLE
How can i active wifi on macOS ?

### ISSUE THREAD

**Issue by tunt-04098** [portrayer/Hackintosh-Ryzen-MSI-B450I#33]
I have same mainboard MSI b450i, my bluetooth work but the wifi don't. How can i make it work ?

**Comment by portrayer** [comment]
intel wifi has no driver in macos, you need to change it to broadcom (dw1820a, dw1560, etc)

**Comment by tunt-04098** [comment]
My fault, I thought you could make the integrated wifi on the mainboard work

**Comment by rozza591** [comment]
> intel wifi has no driver in macos, you need to change it to broadcom (dw1820a, dw1560, etc)

What are you changing to broadcom?

**Comment by Mushmuch** [comment]
Hi Rozza, 
The m.2 slot on the MSI B450i accepts A+E key cards.
I have a BCM94352Z based card which requires the OS to upload the firmware to the card at every boot.
The BCM94360NG cards are supposed to have native bluetooth support out of the box even in Bios and without any additional drivers AND have.
The only issue with these cards is that they are quite expensive on eBay and Ali-express (about 50-60€) and the shipping takes 2 to 3 weeks.

In the meantime, you can try the development [Intel Wifi Drivers](https://github.com/zxystd/itlwm) if you want to help the project and provide crash reports.

**Comment by sqlmap3** [comment]
> intel wifi has no driver in macos, you need to change it to broadcom (dw1820a, dw1560, etc)

inter has driver in macos .

**Comment by sqlmap3** [comment]
> I have same mainboard MSI b450i, my bluetooth work but the wifi don't. How can i make it work ?

[](https://github.com/OpenIntelWireless/HeliPort ),you can download it

**Comment by rozza591** [comment]
> > I have same mainboard MSI b450i, my bluetooth work but the wifi don't. How can i make it work ?
> 
> https://github.com/OpenIntelWireless/HeliPort ,you can [download ](https://github.com/OpenIntelWireless/HeliPort)it

Have you had any luck with the open intel project? I haven't tried in a few months, but when I did I still couldn't get it working.
Tbh all of this is another excuse for me to go to an X570 itx board with dual m.2 slots so I can use a Broadcom adapter. Its a shame as these MSI boards are very good.
