### ISSUE TITLE
Wrong ALCID

### ISSUE THREAD

**Issue by m3rtngs** [portrayer/Hackintosh-Ryzen-MSI-B450I#41]
I believe you are using the wrong ALC ID, I am using 13 and it is working perfectly with the MSI B450i motherboard.

**Comment by portrayer** [comment]
Do your line-in and mic ports work? If don't, there's not much difference between these layouts.
Btw, line-in and mic not working should be a common issue of AppleALC in AMD motherboard.

**Comment by m3rtngs** [comment]
Just checked, line-in and microphone do not work.
