### ISSUE TITLE
MSI B450M Gaming Plus 可以适用吗？

### ISSUE THREAD

**Issue by wqianglxf** [portrayer/Hackintosh-Ryzen-MSI-B450I#47]
- MSI B450M Gaming Plus
- AMD Ryzen 5 2700
- HyperX Fury 16GB 3200MHz DDR4
- Sapphire RX5500XT
- SSD Samsung 970 EVO Plus, 500GB, NVMe
- Fenvi FV-T919 WiFi / Bluetooth Card PCIe
这是我的配置，我计划想安装一台黑苹果，请问可以用您的EFI吗？

**Comment by Goooler** [comment]
@wqianglxf 可以试试

**Comment by portrayer** [comment]
usb map需要重新做，其它小问题不保证
